
app:
    greeting: Springboot Config from configuration server
    version: 2:1
    database: '{  host:"localhost", username:"sezayir", password:"1234"  }'
    environment:
     names: dev,qa,prod
    
mail:
    from: info-config@sezo.com
    hostname: info-config@sezo.com
    port: 8091
 
management:
           endpoints:
            web:
              exposure:
                include: "*"
                
spring:
 profiles:
  active: default  
  
spring.cloud.config.uri: http://localhost:8888